services:
  database:
    image: postgres:17
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      PGDATA: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${DB__PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U user" ]
#      interval: 5s
#      timeout: 3s
#      retries: 3

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "${BROKER__PORT}:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER__USER}
      RABBITMQ_DEFAULT_PASS: ${BROKER__PASSWORD}
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
#    healthcheck:
#      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 30s


# Воркер рабочий, но пока не нужен!

#  worker:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: funds-tracker-worker
#    networks:
#      - dev
#    command: taskiq worker infra:broker -fsd -tp infra.tasks
#    depends_on:
#      - rabbitmq

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "${CACHE__PORT}:6379"
    volumes:
      - cache:/data

  redis_gui:
    container_name: redis-gui
    image: redis/redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/db

volumes:
  pgdata:
  rabbitmq_data:
  cache:
  redisinsight: